python createsegments.py Coastline_social Monet_social
th neural.lua InputContentSegments/Coastline_social_Monet_social_0.jpg InputStyleSegments/Coastline_social_Monet_social_0.jpg Results/Coastline_social_Monet_social_0.jpg 0
th neural.lua InputContentSegments/Coastline_social_Monet_social_1.jpg InputStyleSegments/Coastline_social_Monet_social_1.jpg Results/Coastline_social_Monet_social_1.jpg 0
th neural.lua InputContentSegments/Coastline_social_Monet_social_2.jpg InputStyleSegments/Coastline_social_Monet_social_2.jpg Results/Coastline_social_Monet_social_2.jpg 0
th neural.lua InputContentSegments/Coastline_social_Monet_social_3.jpg InputStyleSegments/Coastline_social_Monet_social_3.jpg Results/Coastline_social_Monet_social_3.jpg 0
th neural.lua InputContentSegments/Coastline_social_Monet_social_4.jpg InputStyleSegments/Coastline_social_Monet_social_4.jpg Results/Coastline_social_Monet_social_4.jpg 0
th neural.lua InputContentSegments/Coastline_social_Monet_social_5.jpg InputStyleSegments/Coastline_social_Monet_social_5.jpg Results/Coastline_social_Monet_social_5.jpg 0
python combinesegments.py Coastline_social Monet_social